### ISSUE TITLE
Hide my ip address

### ISSUE THREAD

**Issue by ghost** [OdiousImp2604/SwayEOS#9]
SUP GAMMERS THIS YA BOY GUCCIKID101. 

Just kidding. Serious issue so you know on the bar at the top of the screen around the network section its shows my ip address. And I basically want to hide it but I cant see anything in config

**Comment by OdiousImp2604** [comment]
Sure! Just replace the format string in ~/.config/waybar/config

Follow the guide here https://github.com/Alexays/Waybar/wiki/Module:-Network

This does not relate to EndeavourOS configs. It is completely to do with waybar. 

Also this repository is outdated use the main one linked in the readme. It will be archived soon.
